<?php

use Illuminate\Support\Str;

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_LOCAL_HOST', 'local'),
            'port' => env('DB_LOCAL_PORT', '3306'),
            'database' => env('DB_LOCAL_DATABASE', 'lms_staging'),
            'username' => env('DB_LOCAL_USERNAME', 'root'),
            'password' => env('DB_LOCAL_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'lms_backend' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'lms_staging'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'sistema_onix' => [ // Conexión adicional para sistema_onix
            'driver' => 'mysql',
            'host' => env('ONIX_DB_HOST', '127.0.0.1'),
            'port' => env('ONIX_DB_PORT', '3306'),
            'database' => env('ONIX_DB_DATABASE', 'lms_staging'),
            'username' => env('ONIX_DB_USERNAME', 'root'),
            'password' => env('ONIX_DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
        'tms' => [ // Conexión adicional para tms
            'driver' => 'mysql',
            'host' => env('TMS_DB_HOST', '127.0.0.1'),
            'port' => env('TMS_DB_PORT', '3306'),
            'database' => env('TMS_DB_DATABASE', 'lms_staging'),
            'username' => env('TMS_DB_USERNAME', 'root'),
            'password' => env('TMS_DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
    ],
    'migrations' => [
        'table' => 'migrations',
        'update_date_on_publish' => true,
    ],
];
