<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class Personal extends Model
{
    use HasUuids;

    protected $fillable = [
        'name',
        'nombres',
        'apellidos',
        'nombre_completo',
        'telefono_oficina',
        'telefono_movil',
        'telefono_casa',
        'correo_electronico',
        'estado_personal',
        'sexo',
        'fecha_nacimiento',
        'estado_civil',
        'sueldo',
        'currency_id',
        'fecha_ingreso_iess',
        'estado_contractual',
        'sectorial',
        'fecha_contrato',
        'fecha_cesante',
        'tiene_licencia',
        'tipo_licencia',
        'puntaje_licencia',
        'direccion_personal',
        'direccion_personal_city',
        'direccion_personal_state',
        'direccion_personal_country',
        'direccion_personal_postalcode',
        'direccion_laboral',
        'direccion_laboral_city',
        'direccion_laboral_state',
        'direccion_laboral_country',
        'direccion_laboral_postalcode',
        'proyecto',
        'area',
        'subarea',
        'cargo_logex',
        'hora_ingreso_laboral',
        'hora_salida_laboral',
        'ingreso1',
        'salida1',
        'ingreso2',
        'salida2',
        'ingreso3',
        'salida3',
        'ingreso4',
        'salida4',
        'ingreso5',
        'salida5',
        'teletrabajo',
        'pago_sueldo',
        'asignacion_multiple',
        'acumula_decimo',
        'acumula_decimo_cuarto',
        'no_marca',
        'nombre_contacto_emergencia',
        'telefono_contacto_emergencia',
        'parentezco_contacto_emergencia',
        'validacion_antecedentes',
        'discapacidad',
        'tipo_pago',
        'assigned_user_id',
    ];

    protected $casts = [
        'fecha_nacimiento' => 'date',
        'fecha_ingreso_iess' => 'date',
        'fecha_contrato' => 'date',
        'fecha_cesante' => 'date',
        'ingreso1' => 'date',
        'salida1' => 'date',
        'ingreso2' => 'date',
        'salida2' => 'date',
        'ingreso3' => 'date',
        'salida3' => 'date',
        'ingreso4' => 'date',
        'salida4' => 'date',
        'ingreso5' => 'date',
        'salida5' => 'date',
        'hora_ingreso_laboral' => 'datetime',
        'hora_salida_laboral' => 'datetime',
        'sueldo' => 'decimal:6',
        'puntaje_licencia' => 'decimal:2',
        'teletrabajo' => 'boolean',
        'pago_sueldo' => 'boolean',
        'asignacion_multiple' => 'boolean',
        'acumula_decimo' => 'boolean',
        'acumula_decimo_cuarto' => 'boolean',
        'no_marca' => 'boolean',
        'validacion_antecedentes' => 'boolean',
        'discapacidad' => 'boolean',
        'deleted' => 'boolean',
    ];
}
